[package]
name = "shutd"
version = "0.1.0"
authors = ["Shimo <shimo.8810@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"

[profile.release]
codegen-units = 1